version: '3.7'

services:
  backend:
    volumes:
      - ./data:/data
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/dist
  docs:
    build:
      context: ./docs
    volumes:
      - docs:/app/_site
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./backend/static:/static
      - ./data:/data
      - frontend:/var/www/frontend
      - docs:/var/www/docs
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - backend
      - frontend
      - docs

volumes:
  static:
  data:
  frontend:
  docs: