version: '3.7'

services:
  backend:
    volumes:
      - ./data:/data
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/dist
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./backend/static:/static
      - ./data:/data
      - frontend:/var/www/frontend
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  data:
  frontend: