# Generated by Django 4.2.6 on 2023-11-15 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='master_projects',
            field=models.ManyToManyField(blank=True, null=True, to='app_indecol.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
