# Generated by Django 4.2.6 on 2024-02-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0002_alter_faq_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
