# Generated by Django 4.2.6 on 2023-11-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0003_group_users_partner_users_person_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='master_projects',
            field=models.ManyToManyField(blank=True, to='app_indecol.project'),
        ),
    ]
