# Generated by Django 4.2.6 on 2024-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0003_faq_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(null=True, to='app_indecol.group'),
        ),
    ]
