# Generated by Django 4.2.6 on 2024-02-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0004_person_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='app_indecol.group'),
        ),
    ]
