# Generated by Django 4.2.6 on 2023-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0004_alter_project_master_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(to='app_indecol.group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(blank=True, to='app_indecol.partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(to='app_indecol.person'),
        ),
    ]
