# Generated by Django 4.2.6 on 2024-02-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0006_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
    ]
