# Generated by Django 4.2.6 on 2023-12-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0007_rename_ressource_resource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='master_projects',
            new_name='related',
        ),
    ]
