# Generated by Django 4.2.6 on 2023-12-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0008_rename_master_projects_project_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.CharField(default='PhD', max_length=50),
        ),
    ]
