# Generated by Django 4.2.6 on 2024-03-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0008_resource_confidential_resource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='value',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='app_indecol.fieldoption'),
        ),
        migrations.AlterField(
            model_name='person',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='app_indecol.group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_keywords_field', to='app_indecol.fieldoption'),
        ),
        migrations.AlterField(
            model_name='project',
            name='methods',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_methods_field', to='app_indecol.fieldoption'),
        ),
        migrations.AlterField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, to='app_indecol.person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
