# Generated by Django 4.2.6 on 2024-03-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0009_alter_category_description_alter_fieldoption_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, to='app_indecol.group'),
        ),
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, to='app_indecol.fieldoption'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(blank=True, to='app_indecol.group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='project_keywords_field', to='app_indecol.fieldoption'),
        ),
        migrations.AlterField(
            model_name='project',
            name='methods',
            field=models.ManyToManyField(blank=True, related_name='project_methods_field', to='app_indecol.fieldoption'),
        ),
        migrations.AlterField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(blank=True, to='app_indecol.person'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
