# Generated by Django 4.2.6 on 2023-12-18 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0009_remove_person_role_person_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('table', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='project',
            name='methods',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_name_field', to='app_indecol.fieldoptions'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_name_field', to='app_indecol.fieldoptions'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_type_field', to='app_indecol.fieldoptions'),
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(to='app_indecol.fieldoptions'),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(related_name='project_keywords_field', to='app_indecol.fieldoptions'),
        ),
        migrations.AddField(
            model_name='project',
            name='methods',
            field=models.ManyToManyField(related_name='project_methods_field', to='app_indecol.fieldoptions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_type_field', to='app_indecol.fieldoptions'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_type_field', to='app_indecol.fieldoptions'),
        ),
    ]
