# Generated by Django 4.2.6 on 2024-03-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0011_user_end_date_user_middle_name_user_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
