# Generated by Django 4.2.6 on 2024-01-12 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0012_team_email_team_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldoptions',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_indecol.category'),
        ),
    ]
