title: IndEcX Documentation
description: Documentation and description for the development details of the IndEcX project
theme: just-the-docs
logo: "/images/logo.png"
favicon_ico: "/images/logo.png"
baseurl: /docs

url: "https://indecx.indecol.no/"

aux_links:
  Repository: https://github.com/NTNU-IndEcol/IndEcX