# Generated by Django 4.2.6 on 2023-10-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0002_alter_project_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.CharField(choices=[('sustainibility', 'SUSTAINIBILITY'), ('car', 'CAR'), ('buildings', 'BUILDINGS'), ('recycling', 'RECYCLING'), ('materials', 'MATERIALS')], max_length=14),
        ),
    ]
