# Generated by Django 4.2.6 on 2023-10-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_indecol", "0004_alter_person_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="persons",
            field=models.ManyToManyField(to="app_indecol.person"),
        ),
    ]
