# Generated by Django 4.2.6 on 2023-10-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_indecol", "0005_project_persons"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Cherubini Group", "Francesco Cherubini Group"),
                            ("Verones Group", "Francesca Verones Group"),
                            ("Stømman Group", "Anders Strømman Group"),
                            ("Hertwich Group", "Edgar Hertwich Group"),
                            ("Müller Group", "Daniel Müller Group"),
                            ("Pettersen Group", "Johan Pettersen Group"),
                            ("Stadler Group", "Konstantin Stadler Group"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("persons", models.ManyToManyField(to="app_indecol.person")),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="groups",
            field=models.ManyToManyField(to="app_indecol.group"),
        ),
    ]
