# Generated by Django 4.2.6 on 2023-10-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_indecol", "0006_group_project_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("M", "Master Project"),
                    ("PhD", "PhD Project"),
                    ("PD", "PostDoc Project"),
                    ("O", "Other type"),
                ],
                default="-",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                choices=[
                    ("Cherubini Group", "Francesco Cherubini Group"),
                    ("Stømman Group", "Anders Strømman Group"),
                    ("Hertwich Group", "Edgar Hertwich Group"),
                    ("Müller Group", "Daniel Müller Group"),
                    ("Pettersen Group", "Johan Pettersen Group"),
                    ("Stadler Group", "Konstantin Stadler Group"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("sintef", "Sintef"),
                            ("equinor", "Equinor"),
                            ("TK", "Trondheim Kommune"),
                            ("PUCP", "Pontificia Universidad Católica del Perú"),
                            ("ETH", "ETH Zürich"),
                            ("SUA", "Sokoine University of Agriculture"),
                            (
                                "Government of the Netherlands",
                                "Government of the Netherlands",
                            ),
                            ("Leiden University", "Leiden University"),
                            ("APRI", "Africa Prolicy Research Institute"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(max_length=2000)),
                ("url", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("University", "University"),
                            ("Private sector", "Private sector"),
                            ("Industry", "Industry"),
                        ],
                        max_length=50,
                    ),
                ),
                ("projects", models.ManyToManyField(to="app_indecol.project")),
            ],
        ),
    ]
