# Generated by Django 4.2.6 on 2023-10-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_indecol", "0007_project_type_alter_group_name_partners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partners",
            name="projects",
        ),
        migrations.AddField(
            model_name="project",
            name="partners",
            field=models.ManyToManyField(to="app_indecol.partners"),
        ),
    ]
