# Generated by Django 4.2.6 on 2023-10-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_indecol", "0008_remove_partners_projects_project_partners"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Partners",
            new_name="Partner",
        ),
    ]
