# Generated by Django 4.2.6 on 2023-10-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_indecol", "0009_rename_partners_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=2000)),
                ("location", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Software", "Software"),
                            ("Article", "Article"),
                            ("Website", "Website"),
                            ("Report", "Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("project", models.ManyToManyField(to="app_indecol.project")),
            ],
        ),
    ]
