# Generated by Django 4.2.6 on 2023-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_indecol", "0012_alter_project_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                choices=[
                    ("Cherubini Group", "Francesco Cherubini Group"),
                    ("Stømman Group", "Anders Strømman Group"),
                    ("Hertwich Group", "Edgar Hertwich Group"),
                    ("Müller Group", "Daniel Müller Group"),
                    ("Pettersen Group", "Johan Pettersen Group"),
                    ("IEDL Group", "Konstantin Stadler Group"),
                ],
                max_length=50,
            ),
        ),
    ]
