# Generated by Django 4.2.6 on 2023-10-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_indecol", "0013_alter_group_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="person_id",
        ),
    ]
