# Generated by Django 4.2.6 on 2023-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_indecol", "0014_remove_person_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(
                choices=[
                    ("sintef", "Sintef"),
                    ("equinor", "Equinor"),
                    ("TK", "Trondheim Kommune"),
                    ("PUCP", "Pontificia Universidad Católica del Perú"),
                    ("ETH", "ETH Zürich"),
                    ("SUA", "Sokoine University of Agriculture"),
                    ("Government of the Netherlands", "Government of the Netherlands"),
                    ("Leiden University", "Leiden University"),
                    ("APRI", "Africa Prolicy Research Institute"),
                    ("No External Partners", "No External Partners"),
                ],
                max_length=50,
            ),
        ),
    ]
