# Generated by Django 4.2.6 on 2023-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_indecol", "0015_alter_partner_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="type",
            field=models.CharField(
                choices=[
                    ("University", "University"),
                    ("Private sector", "Private sector"),
                    ("Industry", "Industry"),
                    ("N/A", "N/A"),
                ],
                max_length=50,
            ),
        ),
    ]
