# Generated by Django 4.2.6 on 2023-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0016_alter_partner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('Cherubini Group', 'Francesco Cherubini Group'), ('Verones Group', 'Francesca Verones Group'), ('Stømman Group', 'Anders Strømman Group'), ('Hertwich Group', 'Edgar Hertwich Group'), ('Müller Group', 'Daniel Müller Group'), ('Pettersen Group', 'Johan Pettersen Group'), ('Ottelin Group', 'Juudit Ottelin Group'), ('IEDL Group', 'Konstantin Stadler Group')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(choices=[('sintef', 'Sintef'), ('equinor', 'Equinor'), ('TK', 'Trondheim Kommune'), ('PUCP', 'Pontificia Universidad Católica del Perú'), ('ETH', 'ETH Zürich'), ('SUA', 'Sokoine University of Agriculture'), ('Government of the Netherlands', 'Government of the Netherlands'), ('Leiden University', 'Leiden University'), ('APRI', 'Africa Prolicy Research Institute'), ('WU', 'Vienna University of Economics and Business'), ('SGS', 'SGS'), ('No External Partners', 'No External Partners')], max_length=50),
        ),
    ]
