# Generated by Django 4.2.6 on 2023-10-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0019_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Master Student', 'Master Student'), ('PhD', 'PhD'), ('PostDoc', 'PostDoc'), ('Enginner', 'Enginner'), ('Associate Professor', 'Associate Professor'), ('Researcher', 'Researcher'), ('Professor', 'Professor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Master Project', 'Master Project'), ('PhD Project', 'PhD Project'), ('PostDoc Project', 'PostDoc Project'), ('Other type', 'Other type'), ('European Project', 'European Project')], default='-', max_length=50),
        ),
    ]
