# Generated by Django 4.2.6 on 2023-10-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0020_alter_person_role_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(related_name='persons', to='app_indecol.person'),
        ),
    ]
