# Generated by Django 4.2.6 on 2023-10-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_indecol', '0022_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='app_indecol.group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(related_name='partners', to='app_indecol.partner'),
        ),
    ]
